import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { TRPCReactProvider } from '~/trpc/react';
import { Header } from '~/components/Header';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="dark">
        <Header />

        <div className="min-h-screen container mx-auto p-4 pt-[56px]">
          <TRPCReactProvider>
            <NuqsAdapter>
              {children}
            </NuqsAdapter>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
